export const BIRTHDAY_DATA = {
    landing: {
        headline: "Happy Birthday, Beautiful.",
        instruction: "Start with the letter first. Then come back for your final surprise.",
        letterButtonLabel: "My Favorite Journal Entry",
        callButtonLabel: "Final Step",
        meetUrl: "https://meet.google.com/drb-qakd-gyu",
    },
    letter: {
        title: "My Favorite Journal Entry",
        date: "19th March 2026",
        paragraphs: [
            "Dear Team Rodha,",
            "I would like to lodge a formal complaint.",
            "I joined your classes with one very simple hope, to place my CAT preparation in safe hands, get a strong score, and somehow drag myself all the way to IIM Ahmedabad without losing my mind in the process.",
            "That was the deal.",
            "You handle Quant, LRDI, VARC, mocks, percentile anxiety, and the slow erosion of my confidence. I handle attendance, homework, and occasional academic humiliation. it was supposed to be a clean arrangement. Professional. Civilized.",
            "At no point in this agreement did I consent to someone quietly entering through your platform and becoming the most distracting, disarming, emotionally expensive part of my life.",
            "And yet, through your institution, I met her,",
            "SNEHAL.",
            "It did not even begin suspiciously. There was no filmy drama. No cinematic entry. No universe shifting moment. It began in the most innocent way possible. Books. She got me with books!! ",
            "And then came doubts. Then more doubts. Very normal. Very safe. Very educational.",
            "LIES !!!!!!!",
            "Because somewhere between solving questions and explaining them, I made a terrible mistake.",
            "I kept replying.\nAnd she kept coming back.",
            "At first, I thought I was simply helping a classmate. You know, the usual academic charity. A doubt here, a concept there, one more explanation because clearly my engineering degree had finally found a noble purpose.",
            "Instead, your classes created a situation.",
            "I was accused, called an owl, a senile geezer, millenial. She behaved like a toddler, menace, little suspect. I got to know, very firmly, that thumbs up reactions are rude. That unsending messages is criminal behaviour. That “bye” should be mutual. That I sounded cold when I did not mean to. That I needed to be the interesting version of myself, as if she had somehow met multiple editions and was dissatisfied with the current release.",
            "In saying all of this, she was somehow still the sweetest person in the room.",
            "I ask you honestly, what kind of CAT institute allows this level of interference with a man’s personality? Huh ?",
            "And the worst part is, she is usually right. That is the real problem. She has this unsettling ability to see where I was present and where I was only pretending to be.",
            "Then, naturally, things got worse. Yes, worse!!",
            "She stopped being “someone from class.” She became routine. Then comfort. Then expectation. Then the first person I wanted to tell things to. Then the person whose silence I noticed too fast. Then the person whose moods started affecting mine without permission.",
            "I wanted her to eat, sleep, show up, try again, and stop speaking about herself like she was permanently behind everyone else.",
            "I still blame you guys for this, because this is the part where this stops being funny, at least for me.",
            "I loved her. \nNot in the “nice girl, nice conversations, nice timing” way.",
            "I loved her in the way where I wanted more of her in every form I could get. In messages. In calls. In the quiet parts of life. In the future I was too careful to describe out loud. I wanted her around me the way people want home around them, not occasionally, but naturally.",
            "Your so called educational institution did all this, because of you people, that I was distracted in such a way, its beacuse of you that",
            "A joke mattered more.\nA small misunderstanding hurt more.\nA missed reply stretched longer.",
            "I wish I could say I handled that beautifully. But I didnt, I loved her with more fear than maturity sometimes. And if there is anything I feel most honestly, it is this, that beneath all my stupidity, my ego, my bad timing, and my badly worded reactions, what I feel for her is real.",
            "Painfully real. The sort of real that does not disappear just because it becomes difficult.",
            "So yes, this thing is formally supposed to be a complaint. And technically, it still is. But it is also, unfortunately for the integrity of my complaint, one of the best things that has ever happened to me.",
            "She gave me what I didnt have, what I couldnt have. \nLife, for a while, felt brighter with her in it.",
            "Despite all the damage, that your platform is responsible for, I would still choose the version of my life in which I met her, again and again, if I could.",
            "So thank you, I suppose.\nYou promised me CAT preparation in safe hands.\nInstead, you placed my heart in very unsafe ones.",
            "And I have never really recovered."
        ],
        signOff: "Yours truly,\nApoorv",
        images: [
            { url: "Snehal bday/1- The first thing she shared.jpg", date: "", memory: "The first thing she shared" },
            { url: "Snehal bday/2- She likes chai! .jpg", date: "", memory: "She likes chai!" },
            { url: "Snehal bday/3- No, She LOVES chai !!.jpg", date: "", memory: "No, She LOVES chai !!" },
            { url: "Snehal bday/4- If only I could show my mother.jpg", date: "", memory: "If only I could show my mother" },
            { url: "Snehal bday/5- She makes me do strange things.jpg", date: "", memory: "She makes me do strange things" },
            { url: "Snehal bday/6- She's about to leave ;(.jpg", date: "", memory: "She's about to leave ;(" },
            { url: "Snehal bday/7- Hope she loves the vacation.jpg", date: "", memory: "Hope she loves the vacation" },
            { url: "Snehal bday/8- Did I mention that she LOVES food!.jpg", date: "", memory: "Did I mention that she LOVES food!" },
            { url: "Snehal bday/9- And then she left again.jpg", date: "", memory: "And then she left again" },
            { url: "Snehal bday/10- Atleast I get to see her now.jpg", date: "", memory: "Atleast I get to see her now" },
            { url: "Snehal bday/11- Its the best part of my day.jpg", date: "", memory: "Its the best part of my day" },
            { url: "Snehal bday/12- completely unhinged, completely her.jpg", date: "", memory: "completely unhinged, completely her" },
            { url: "Snehal bday/13- The problem is she's beautiful.jpg", date: "", memory: "The problem is she's beautiful" },
            { url: "Snehal bday/14- Wish I could be there with her.jpg", date: "", memory: "Wish I could be there with her" },
            { url: "Snehal bday/15- In any way possible, just remind her of me.jpg", date: "", memory: "In any way possible, just remind her of me" },
            { url: "Snehal bday/16- She loves cats!!.jpg", date: "", memory: "She loves cats!!" },
            { url: "Snehal bday/17- And yes, Dogs too.jpg", date: "", memory: "And yes, Dogs too" },
            { url: "Snehal bday/18- She's sees beauty through a lens.jpg", date: "", memory: "She's sees beauty through a lens" },
            { url: "Snehal bday/19- knits like she's always known how.jpg", date: "", memory: "knits like she's always known how" },
            { url: "Snehal bday/20- and codes, what!!  she made this for me.jpg", date: "", memory: "and codes, what!!  she made this for me" },
            { url: "Snehal bday/21- That look deserves its own frame. Wait, This could be made professional...jpg", date: "", memory: "That look deserves its own frame" },
            { url: "Snehal bday/22- Her new snapchat fav, cant blame, looks cute.jpg", date: "", memory: "Her new snapchat fav, cant blame, looks cute" },
            { url: "Snehal bday/23- May this, never happen again. I wont let it.jpg", date: "", memory: "May this, never happen again. I wont let it" },
            { url: "Snehal bday/24- She got something from me.jpg", date: "", memory: "She got something from me" },
            { url: "Snehal bday/25- She looked prettier than all of it.jpg", date: "", memory: "She looked prettier than all of it" },
            { url: "Snehal bday/26- Most of all, she's mad at me.jpg", date: "", memory: "Most of all, she's mad at me" },
            { url: "Snehal bday/27- The day she finally lets go.jpg", date: "", memory: "The day she finally lets go" },
            { url: "Snehal bday/28- I worry even when she's safe.jpg", date: "", memory: "I worry even when she's safe" },
            { url: "Snehal bday/29- Just a little Toddler !!.jpg", date: "", memory: "Just a little Toddler !!" },
            { url: "Snehal bday/30- She brings the best out of me.jpg", date: "", memory: "She brings the best out of me" },
            { url: "Snehal bday/31- Happy Birthday, Sweetie. I Love You.jpg", date: "", memory: "Happy Birthday, Sweetie. I Love You." }
        ]
    }
};
